-- Прямой SQL-импорт словаря из PZMVP/data.csv (без LOAD DATA INFILE)
SET NAMES utf8mb4;
SET time_zone = '+00:00';
USE sibword_db;

INSERT INTO languages (code, name, is_active, created_at, updated_at)
SELECT 'bxr', 'Бурятский язык', 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM languages WHERE code = 'bxr');

SET @lang_id := (SELECT id FROM languages WHERE code = 'bxr' LIMIT 1);

INSERT INTO lexemes (language_id, word, translation, transcription, complexity_index, status, created_at, updated_at)
SELECT @lang_id, src.word, src.translation, NULL, 0.00, 'published', NOW(), NOW()
FROM (
    SELECT 'hайн' AS word, 'добрый' AS translation
    UNION ALL SELECT 'hалхитай', 'ветреный'
    UNION ALL SELECT 'hүүшэ', 'долото (хабтагар)'
    UNION ALL SELECT 'hүхэ', 'топор'
    UNION ALL SELECT 'hэлюур', 'весла (hэльбүүр'
    UNION ALL SELECT 'hэрээ', 'острога'
    UNION ALL SELECT 'аадар', 'ливень'
    UNION ALL SELECT 'агаар', 'воздух'
    UNION ALL SELECT 'ажаллаха', 'трудиться'
    UNION ALL SELECT 'Алтан Гадаһан', 'Полярная звезда'
    UNION ALL SELECT 'алха', 'молоток'
    UNION ALL SELECT 'амарха', 'отдыхать'
    UNION ALL SELECT 'амһарта', 'аяга табаг'
    UNION ALL SELECT 'амтатай', 'вкусный'
    UNION ALL SELECT 'анзаhан', 'соха'
    UNION ALL SELECT 'арбан', 'десять'
    UNION ALL SELECT 'арбан гурба', 'тринадцать'
    UNION ALL SELECT 'арбан долоо', 'семнадцать'
    UNION ALL SELECT 'арбан дүрбэ', 'четырнадцать'
    UNION ALL SELECT 'арбан зургаа', 'шестнадцать'
    UNION ALL SELECT 'арбан найма', 'восемнадцать'
    UNION ALL SELECT 'арбан нэгэн', 'одиннадцать'
    UNION ALL SELECT 'арбан таба', 'пятнадцать'
    UNION ALL SELECT 'арбан хоёр', 'двенадцать'
    UNION ALL SELECT 'арбан юhэн', 'девятнадцать'
    UNION ALL SELECT 'аршаха', 'вытирать'
    UNION ALL SELECT 'аршуул', 'тряпка; полотенце (аршуур)'
    UNION ALL SELECT 'аса', 'вилы (штармааг)'
    UNION ALL SELECT 'асууха', 'спрашивать'
    UNION ALL SELECT 'аяга', 'чаша; чашка; стакан'
    UNION ALL SELECT 'байгаали', 'природа'
    UNION ALL SELECT 'балта', 'молот; кувалда'
    UNION ALL SELECT 'бархирха', 'плакать'
    UNION ALL SELECT 'баян', 'богатый'
    UNION ALL SELECT 'баярлаха', 'радоваться'
    UNION ALL SELECT 'биирэ', 'кисточка (кисточкэ)'
    UNION ALL SELECT 'богони', 'короткий'
    UNION ALL SELECT 'богоһо', 'порог'
    UNION ALL SELECT 'бодохо', 'решать; думать / вставать'
    UNION ALL SELECT 'бордоһон', 'вьюга; буран; метель'
    UNION ALL SELECT 'борной', 'борона'
    UNION ALL SELECT 'боро хараан', 'сумерки'
    UNION ALL SELECT 'бороон', 'дождь'
    UNION ALL SELECT 'бороотой', 'дождливый'
    UNION ALL SELECT 'буд нэхэдэг станок', 'ткацкий станок'
    UNION ALL SELECT 'буу', 'ружьё'
    UNION ALL SELECT 'бүгжэ', 'скоба (таталга түмэр)'
    UNION ALL SELECT 'бүгшэм', 'спёртый; душный; безветренный'
    UNION ALL SELECT 'бүдүүн', 'тарган'
    UNION ALL SELECT 'бүлюу', 'точило (тээрмэ'
    UNION ALL SELECT 'бүрхэг', 'пасмурный; облачный'
    UNION ALL SELECT 'бэлигтэй', 'талантливый'
    UNION ALL SELECT 'бэшэхэ', 'писать'
    UNION ALL SELECT 'газар хүдэлэлгэ', 'землетрясение'
    UNION ALL SELECT 'гамнаха', 'беречь'
    UNION ALL SELECT 'ган', 'засуха'
    UNION ALL SELECT 'гарагай гурбан', 'Мягмар гараг'
    UNION ALL SELECT 'гарагай долоон', 'Бямба гараг'
    UNION ALL SELECT 'гарагай дүрбэн', 'Лхагва гараг'
    UNION ALL SELECT 'гарагай зургаан', 'Баасан гараг'
    UNION ALL SELECT 'гарагай нэгэн', 'Ням гараг'
    UNION ALL SELECT 'гарагай табан', 'Пүрэв гараг'
    UNION ALL SELECT 'гарагай хоёр', 'Даваа гараг'
    UNION ALL SELECT 'гараха', 'выходить'
    UNION ALL SELECT 'гашуун', 'горький'
    UNION ALL SELECT 'годли', 'стрела (hурша)'
    UNION ALL SELECT 'гохо', 'багор; крючок'
    UNION ALL SELECT 'губшуур', 'невод'
    UNION ALL SELECT 'гуламта', 'очаг'
    UNION ALL SELECT 'гунгарбаа', 'божница'
    UNION ALL SELECT 'гуниглаха', 'грустить'
    UNION ALL SELECT 'гурбадахи', 'третий'
    UNION ALL SELECT 'гурбан', 'три'
    UNION ALL SELECT 'гурбан зуун', 'триста'
    UNION ALL SELECT 'гушан', 'тридцать'
    UNION ALL SELECT 'гушан нэгэн', 'тридцать один'
    UNION ALL SELECT 'гүйхэ', 'бежать'
    UNION ALL SELECT 'гүсэ', 'чайник'
    UNION ALL SELECT 'гэмэрхэ', 'ворчать'
    UNION ALL SELECT 'гэр', 'дом'
    UNION ALL SELECT 'гэрэл', 'зеркало; свет'
    UNION ALL SELECT 'гэшхүүр', 'лесенка; ступенька'
    UNION ALL SELECT 'далай', 'море'
    UNION ALL SELECT 'далан', 'семьдесят'
    UNION ALL SELECT 'далан нэгэн', 'семьдесят один'
    UNION ALL SELECT 'долоон', 'семь'
    UNION ALL SELECT 'Долоон Үбгэд', 'Семь старцев (Б. Медведица)'
    UNION ALL SELECT 'долоон хоног', 'неделя'
    UNION ALL SELECT 'дулаан', 'тепло'
    UNION ALL SELECT 'дулаан', 'теплый'
    UNION ALL SELECT 'дурhан үрэбшэ', 'мочало (угаадаг дурhан)'
    UNION ALL SELECT 'духаряан', 'чарка'
    UNION ALL SELECT 'дүрбэдэхи', 'четвёртый'
    UNION ALL SELECT 'дүрбэн', 'четыре'
    UNION ALL SELECT 'дүтын', 'близкий'
    UNION ALL SELECT 'дүшэ', 'наковальня'
    UNION ALL SELECT 'дүшэн', 'сорок'
    UNION ALL SELECT 'дүшэн нэгэн', 'сорок один'
    UNION ALL SELECT 'дэбхэрхэ', 'прыгать'
    UNION ALL SELECT 'дэрэ', 'изголовье; подушка'
    UNION ALL SELECT 'ерэ нэгэн', 'девяносто один'
    UNION ALL SELECT 'ерэн', 'девяносто'
    UNION ALL SELECT 'ерэхэ', 'приходить'
    UNION ALL SELECT 'жаахан', 'маленький'
    UNION ALL SELECT 'жабар', 'мороз; холод'
    UNION ALL SELECT 'жада', 'копьё'
    UNION ALL SELECT 'жалабша', 'неглубокий котёл'
    UNION ALL SELECT 'жаран', 'шестьдесят'
    UNION ALL SELECT 'жаран нэгэн', 'шестьдесят один'
    UNION ALL SELECT 'жорлон', 'уборная; отхожее место'
    UNION ALL SELECT 'жэл', 'год'
    UNION ALL SELECT 'зада', 'ненастье; непогода'
    UNION ALL SELECT 'залин', 'гром с молнией'
    UNION ALL SELECT 'залинта аадар', 'дуутай аадар'
    UNION ALL SELECT 'зоригтой', 'мужественный'
    UNION ALL SELECT 'зун', 'лето'
    UNION ALL SELECT 'зуһалан', 'летник'
    UNION ALL SELECT 'зургаан', 'ёргоон'
    UNION ALL SELECT 'зуун', 'сто'
    UNION ALL SELECT 'зуун нэгэн', 'сто один'
    UNION ALL SELECT 'зүрхэтэй', 'смелый'
    UNION ALL SELECT 'зүүн', 'иголка'
    UNION ALL SELECT 'зѳѳлэн', 'мягкий'
    UNION ALL SELECT 'лонхо', 'бутыль; бутылка'
    UNION ALL SELECT 'мадага', 'большой нож'
    UNION ALL SELECT 'манна(н)', 'туман'
    UNION ALL SELECT 'модон', 'деревянный'
    UNION ALL SELECT 'модон гадаhан', 'мотыга'
    UNION ALL SELECT 'муу', 'плохой'
    UNION ALL SELECT 'мүндэр', 'град'
    UNION ALL SELECT 'мүнөөдэр', 'сегодня'
    UNION ALL SELECT 'мүрэн', 'река (большая)'
    UNION ALL SELECT 'мүшэн', 'звезда'
    UNION ALL SELECT 'мэргэн', 'меткий'
    UNION ALL SELECT 'мянга', 'тысяча'
    UNION ALL SELECT 'наадаха', 'играть'
    UNION ALL SELECT 'набтар', 'низкий'
    UNION ALL SELECT 'найман', 'восемь'
    UNION ALL SELECT 'намар', 'осень'
    UNION ALL SELECT 'намарай', 'осенний'
    UNION ALL SELECT 'наран', 'Солнце'
    UNION ALL SELECT 'нарин', 'тонкий'
    UNION ALL SELECT 'ная', 'восемьдесят'
    UNION ALL SELECT 'наян нэгэ', 'восемьдесят один'
    UNION ALL SELECT 'нёдондо', 'в прошлом году'
    UNION ALL SELECT 'номгон', 'спокойный'
    UNION ALL SELECT 'номо', 'лук (оружие)'
    UNION ALL SELECT 'нуур', 'озеро'
    UNION ALL SELECT 'нүгөөдэр', 'послезавтра'
    UNION ALL SELECT 'нэгэдэхи', 'первый'
    UNION ALL SELECT 'нэгэн', 'один'
    UNION ALL SELECT 'няаха', 'клеить'
    UNION ALL SELECT 'һайндэрлэхэ', 'праздновать'
    UNION ALL SELECT 'һалхин', 'ветер'
    UNION ALL SELECT 'һара', 'луна'
    UNION ALL SELECT 'һолонго', 'радуга'
    UNION ALL SELECT 'һураха', 'учиться / спрашивать'
    UNION ALL SELECT 'һууха', 'сидеть'
    UNION ALL SELECT 'һүни', 'ночь'
    UNION ALL SELECT 'һүүдэр', 'тень'
    UNION ALL SELECT 'һэеы гэр', 'войлочная юрта'
    UNION ALL SELECT 'һэрихэ', 'просыпаться'
    UNION ALL SELECT 'һэрээ', 'шүбгэ'
    UNION ALL SELECT 'һэрюун', 'прохладный'
    UNION ALL SELECT 'огторгой', 'небо; небосвод'
    UNION ALL SELECT 'огторгойн хаяа', 'горизонт'
    UNION ALL SELECT 'ой', 'лес'
    UNION ALL SELECT 'ооголхо', 'звать'
    UNION ALL SELECT 'оргоожо хамуур', 'швабра'
    UNION ALL SELECT 'орон', 'кровать'
    UNION ALL SELECT 'орохо', 'заходить'
    UNION ALL SELECT 'пеэшэн', 'печь'
    UNION ALL SELECT 'саhатай', 'снежный'
    UNION ALL SELECT 'саарhан', 'бумажный'
    UNION ALL SELECT 'сабшуур', 'тяпка'
    UNION ALL SELECT 'саһан', 'снег'
    UNION ALL SELECT 'сахилгаан', 'молния'
    UNION ALL SELECT 'сая', 'миллион'
    UNION ALL SELECT 'сонхо', 'шагаабари'
    UNION ALL SELECT 'сухалдаха', 'сердиться'
    UNION ALL SELECT 'сэбэр', 'чистый'
    UNION ALL SELECT 'сэбэрлэхэ', 'чистить'
    UNION ALL SELECT 'сэлмэг', 'ясная погода'
    UNION ALL SELECT 'сэлмэг', 'ясный'
    UNION ALL SELECT 'сэсэн', 'умный'
    UNION ALL SELECT 'таалаха', 'целовать'
    UNION ALL SELECT 'табаг', 'тарелка'
    UNION ALL SELECT 'табадахи', 'пятый'
    UNION ALL SELECT 'табан', 'пять'
    UNION ALL SELECT 'табин', 'пятьдесят'
    UNION ALL SELECT 'табин нэгэн', 'пятьдесят один'
    UNION ALL SELECT 'табхансаг', 'табхаансаг'
    UNION ALL SELECT 'табюур', 'маленький столик / табурет'
    UNION ALL SELECT 'таг', 'полка настенная'
    UNION ALL SELECT 'тала', 'степь'
    UNION ALL SELECT 'тала газар', 'равнина'
    UNION ALL SELECT 'тамарха', 'плавать'
    UNION ALL SELECT 'тармуул', 'грабли (тармуур)'
    UNION ALL SELECT 'тогоон', 'котёл'
    UNION ALL SELECT 'томо', 'большой'
    UNION ALL SELECT 'тоншохо', 'стучать'
    UNION ALL SELECT 'торхо', 'кадка; бочка; остов'
    UNION ALL SELECT 'тулга', 'треножник'
    UNION ALL SELECT 'туранхай', 'худой'
    UNION ALL SELECT 'түйсэ', 'туесок из бересты'
    UNION ALL SELECT 'түмпэн', 'таз; миска'
    UNION ALL SELECT 'түмэн', 'десять тысяч'
    UNION ALL SELECT 'түмэр', 'железный'
    UNION ALL SELECT 'түргэн', 'быстрый'
    UNION ALL SELECT 'тэбшэ', 'деревянное блюдо'
    UNION ALL SELECT 'тэгнүүр', 'коромысло'
    UNION ALL SELECT 'тэнгэри', 'небо'
    UNION ALL SELECT 'тэнгэриин дуун', 'гром'
    UNION ALL SELECT 'тэнэг', 'глупый'
    UNION ALL SELECT 'тээрмэ', 'мельница'
    UNION ALL SELECT 'угааха', 'стирать'
    UNION ALL SELECT 'угтаха', 'встречать'
    UNION ALL SELECT 'удам', 'ширь; просторы'
    UNION ALL SELECT 'уларил', 'климат; погода'
    UNION ALL SELECT 'улхансаг', 'чаша деревянная'
    UNION ALL SELECT 'унаха', 'падать'
    UNION ALL SELECT 'унтари', 'постель'
    UNION ALL SELECT 'унтаха', 'спать'
    UNION ALL SELECT 'уншаха', 'читать'
    UNION ALL SELECT 'уняа', 'стропила'
    UNION ALL SELECT 'урадхал', 'течение'
    UNION ALL SELECT 'урзанда', 'в позапрошлом году'
    UNION ALL SELECT 'урса', 'конусообразный шалаш; чум'
    UNION ALL SELECT 'ута', 'длинный'
    UNION ALL SELECT 'үбдэхэ', 'болеть'
    UNION ALL SELECT 'үбэл', 'зима'
    UNION ALL SELECT 'үбэлжөөн', 'зимник'
    UNION ALL SELECT 'үглөөгүүр', 'утро'
    UNION ALL SELECT 'үгытэй', 'бедный'
    UNION ALL SELECT 'үдхэн', 'густой'
    UNION ALL SELECT 'үдьхэлхэ', 'пинать'
    UNION ALL SELECT 'үдэр', 'день'
    UNION ALL SELECT 'үдэшэ', 'вечер'
    UNION ALL SELECT 'үдэшэхэ', 'провожать'
    UNION ALL SELECT 'үер', 'наводнение'
    UNION ALL SELECT 'үзэхэ', 'изучать'
    UNION ALL SELECT 'үлирбэ', 'клещи; щипцы; кусачки'
    UNION ALL SELECT 'үндэр', 'высокий'
    UNION ALL SELECT 'үргэбшэ', 'коромысло (тэлүүр'
    UNION ALL SELECT 'үргэн', 'широкий'
    UNION ALL SELECT 'үрхэ', 'дымовое отверстие'
    UNION ALL SELECT 'үсэгэлдэр', 'вчера'
    UNION ALL SELECT 'үтэг', 'усадьба'
    UNION ALL SELECT 'үүдэн', 'дверь; ворота'
    UNION ALL SELECT 'үүлэн', 'облако; туча'
    UNION ALL SELECT 'үүр', 'утренняя заря; рассвет'
    UNION ALL SELECT 'үүр хираан', 'предрассветные сумерки'
    UNION ALL SELECT 'үхэг', 'низенький шкаф; подставка; ящик'
    UNION ALL SELECT 'хабар', 'весна'
    UNION ALL SELECT 'хада', 'уула'
    UNION ALL SELECT 'хадааhан', 'гвоздь'
    UNION ALL SELECT 'хадаха', 'прибивать'
    UNION ALL SELECT 'хадуур', 'серп (сээрпэ'
    UNION ALL SELECT 'хажуур', 'коса'
    UNION ALL SELECT 'хайша', 'ножницы'
    UNION ALL SELECT 'халуун', 'горячий; жаркий'
    UNION ALL SELECT 'халуун', 'жаркий'
    UNION ALL SELECT 'хамуур', 'веник (шэрбүүр'
    UNION ALL SELECT 'хамуур', 'метла'
    UNION ALL SELECT 'хана', 'стена'
    UNION ALL SELECT 'хангил', 'гольцы'
    UNION ALL SELECT 'ханза', 'сундук'
    UNION ALL SELECT 'харааха', 'ругать'
    UNION ALL SELECT 'хараха', 'смотреть'
    UNION ALL SELECT 'харуул', 'рубанок'
    UNION ALL SELECT 'харюусаха', 'отвечать'
    UNION ALL SELECT 'хатуу', 'твердый'
    UNION ALL SELECT 'хахуули', 'удочка'
    UNION ALL SELECT 'хашхарха', 'кричать'
    UNION ALL SELECT 'хиибараан', 'ненастье; непогода'
    UNION ALL SELECT 'хинуур', 'стамеска (hүүшэ)'
    UNION ALL SELECT 'хоёр', 'два'
    UNION ALL SELECT 'хоёр зуун', 'двести'
    UNION ALL SELECT 'хоёр мянга', 'две тысячи'
    UNION ALL SELECT 'хоёр түмэн', 'двадцать тысяч'
    UNION ALL SELECT 'хоёрдохи', 'второй'
    UNION ALL SELECT 'холын', 'дальний'
    UNION ALL SELECT 'хомор', 'редкий'
    UNION ALL SELECT 'хорин', 'двадцать'
    UNION ALL SELECT 'хорин нэгэн', 'двадцать один'
    UNION ALL SELECT 'хорин хоер', 'двадцать два'
    UNION ALL SELECT 'хотон', 'загон; хлев'
    UNION ALL SELECT 'худаг', 'колодец'
    UNION ALL SELECT 'хургабша', 'напёрсток (хурабша)'
    UNION ALL SELECT 'хутага', 'нож'
    UNION ALL SELECT 'хутага', 'нож (хотиго)'
    UNION ALL SELECT 'хүдэлхэ', 'работать / двигаться'
    UNION ALL SELECT 'хүйтэн', 'холод'
    UNION ALL SELECT 'хүйтэн', 'холодный'
    UNION ALL SELECT 'хүлисэхэ', 'простить'
    UNION ALL SELECT 'хүрзэ', 'лопата (хүрзэгэ)'
    UNION ALL SELECT 'хүсэтэй', 'сильный'
    UNION ALL SELECT 'хэбтэри', 'ложе; постель; лежанка'
    UNION ALL SELECT 'хэбтэхэ', 'лежать'
    UNION ALL SELECT 'хэдэргэ', 'кожемялка'
    UNION ALL SELECT 'хюруу', 'сэн'
    UNION ALL SELECT 'хюрѳѳ', 'пила (хүреэ)'
    UNION ALL SELECT 'шабартай', 'глинистый'
    UNION ALL SELECT 'шабдаа', 'разделочная доска'
    UNION ALL SELECT 'шадамар', 'умелый'
    UNION ALL SELECT 'шанага', 'ковш'
    UNION ALL SELECT 'шанаха', 'варить'
    UNION ALL SELECT 'шахуурга', 'пресс'
    UNION ALL SELECT 'шуран', 'ловкий'
    UNION ALL SELECT 'шуурга(н)', 'буря'
    UNION ALL SELECT 'шүбгэ', 'шило'
    UNION ALL SELECT 'шүүдэр', 'роса'
    UNION ALL SELECT 'шэгнүүр', 'весы'
    UNION ALL SELECT 'шэл', 'стеклянный'
    UNION ALL SELECT 'шэлээбэри', 'кочерга'
    UNION ALL SELECT 'шэнгэн', 'жидкий'
    UNION ALL SELECT 'шэрдэг', 'матрац; тюфяк'
    UNION ALL SELECT 'шэрүүн', 'жесткий'
    UNION ALL SELECT 'шэрээ', 'низкий стол; деревянная кровать'
    UNION ALL SELECT 'эдихэ', 'есть'
    UNION ALL SELECT 'эдэгэхэ', 'выздороветь'
    UNION ALL SELECT 'элhэтэй', 'песочный'
    UNION ALL SELECT 'элһэн', 'песок'
    UNION ALL SELECT 'элюур', 'утюг'
    UNION ALL SELECT 'энеэхэ', 'смеяться'
    UNION ALL SELECT 'ээрүүл', 'прялка (ээрсэг)'
    UNION ALL SELECT 'юhэн', 'девять'
    UNION ALL SELECT 'юртэмсэ', 'мир; вселенная'
    UNION ALL SELECT 'ябаган бордоһон', 'позёмка'
    UNION ALL SELECT 'ябаха', 'идти; ехать'
) AS src
WHERE NOT EXISTS (
    SELECT 1 FROM lexemes l
    WHERE l.language_id = @lang_id
      AND l.word = src.word
      AND l.translation = src.translation
);

SELECT COUNT(*) AS total_lexemes_bxr FROM lexemes WHERE language_id = @lang_id;
